[package]
name = "hamming"
version = "0.1.0"
authors = ["Pierre Avital <pierre.avital@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
ffi = []
default = ["ffi"]

[lib]
name = "secded"
crate-type = ["staticlib", "dylib"]
